### ISSUE TITLE
Feature require

### ISSUE THREAD

**Issue by ed29** [Cywaithaka/product_minimum_order#1]
Hi:
I am useing odoo 10,this addon is useful to me and i need it,would you please help me to port it to odoo 10?Thank you very much.

**Comment by Cywaithaka** [comment]
Hi. Sorry, I did not see this on time. Did you get the help that you needed?

**Comment by ed29** [comment]
@Cywaithaka Not yet.

**Comment by Cywaithaka** [comment]
Please drop me an email on cygawa@gmail.com.
